### ISSUE TITLE
Error occurred

### ISSUE THREAD

**Issue by luto65** [nrekretep/pikturr#2]
![output-file](https://cloud.githubusercontent.com/assets/2243367/26175443/fe483f58-3b52-11e7-93c8-7dd83ac9775f.png)

**Comment by luto65** [comment]
that error was obtained by executing the command in example, after proper installation
node index.js 'http://petstore.swagger.io/v2/swagger.yaml'

**Comment by antonyh** [comment]
You could try this variant: https://github.com/antonyh/pikturr

I've removed all the node_modules and put them into 'package.json' - a side effect is updated versions to latest. It could be that something is outdated, or OS specific so it doesn't work on Mac - if that's the case, then my fork might solve this for you. It certainly worked for me (Linux Subsystem for Windows)

**Comment by nrekretep** [comment]
The corresponding PR which put the dependencies into "package.json" has been merged.
