### ISSUE TITLE
add missing licence file

### ISSUE THREAD

**Issue by sebastian-schmid** [nrekretep/pikturr#8]
Hi @nrekretep,

would be great if this repo gets a licence file to clarify the rights and duties of the software.

I suggest GPL 3.0 as an appropriate licence.

kindly regards,
Sebastian

**Comment by adrolet** [comment]
I concur A license statement would be great.

For an environment like mine (Corporate) I would suggest double licensing.
GPL 2 or 3 with be a good fit for pure Open Source project.
But something like MIT style of Apache would provide more flexibility for projects that mix open and close source.

In the end this is up to Peter.

**Comment by nrekretep** [comment]
Hi Sebastian, hi Alain,
thanks bringing up the license issue. 
I chose the MIT license because the most other projects pikturr depends on (plantuml-encoder, swagger-parser, swagger-methods) use this license too and seems sufficent for this project.
